config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'questions#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  
  resources :questions do
    resources :comments, only: [:new, :create, :edit, :update, :destroy] do
      resources :sub_comments, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  namespace :admin do
    resources :questions, only: [:show, :destroy] do
      resources :answers, only: [:create, :edit, :update, :destroy]
      resources :comments, only: [:new, :create, :edit, :update, :destroy] do
        resources :sub_comments, only: [:new, :create, :edit, :update, :destroy]
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  validates_presence_of :content, :user_id

  belongs_to :user
  has_one :answer, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :sub_comments, through: :comments
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  def show
    @question = Question.includes(:answer).find(params[:id])
    @comments = @question.comments
    @answer = Answer.new
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.order(:created_at)
  end

  def show
    @question = Question.find(params[:id])
    @comments = @question.comments
  end

  def new
    return render file: '/public/404.html' unless !!current_user
    @question = Question.new
  end

  def create
    @question = current_user.questions.create(question_params)
    if @question.save
      redirect_to question_path(@question)
    else
      render :new
    end
  end

  def edit
    return render file: '/public/404.html' unless !!current_user
    @question = current_user.questions.find(params[:id])
  end

  def update
    @question = current_user.questions.find(params[:id])
    if @question.update(question_params)
      redirect_to question_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question = current_user.questions.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private
  
  def question_params
    params.require(:question).permit(:content)
  end
end

app/views/admin/questions/show.html.erb
<div class="button-margin">
  <div class="center-align post-q admin-c-button-row">
    <%= button_to "Post a Comment", new_admin_question_comment_path(@question), method: "get", class: "admin-button" %>
    <%= button_to "Delete", admin_question_path(@question), method: "delete", class: "admin-button" %>
  </div>
</div>
<main class="show-admin-q">
  <div class="row card-rows center-align">
    <div class="col s6" style="width:100%">
      <div class="card teal">
        <div class="card-content white-text">
          <p><%= @question.content %></p></br>
          <p>Submitted by: <%= @question.user.first_name.capitalize %> <%= @question.user.last_name.capitalize[0] %>.</p>
        </div>
      </div>
    </div>
  </div>
  <div class="row card-rows center-align">
    <% if @question.answer %>
      <div class="col s6" style="width:100%">
        <div class="card blue">
          <div class="card-content white-text" id="answer">
            <p><%= @question.answer.content %></p></br>
            <p>Answered by: <%= @question.answer.user.first_name.capitalize %> <%= @question.answer.user.last_name.capitalize[0] %>.</p>
            <div class="card-action remove-margin">
              <%= link_to "Edit", edit_admin_question_answer_path(@question, @question.answer) %>
              <%= link_to "Delete", admin_question_answer_path(@question, @question.answer), method: 'delete' %>
            </div>
          </div>
        </div>
      </div>
    <% else %>
      <div class="col s6" style="width:100%">
        <div class="card answer-border">
          <div class="card-content black-text">
            <%= render partial: 'admin/answers/form' %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</main>
<section>
  <% @comments.each_with_index do |comment, index| %>
    <div class="center-align show-c" id="comment-<%= index + 1 %>">
      <div class="col s12 comment-size">
        <% if comment.user.admin? %>
          <div class="card blue">
        <% else %>
          <div class="card amber">
        <% end %>
          <div class="card-content white-text">
            <p><%= comment.content %></p></br>
            <p>Submitted by: <%= comment.user.first_name.capitalize %> <%= comment.user.last_name.capitalize[0] %>.</p>
          </div>
          <%= button_to "Post a Sub-Comment", new_admin_question_comment_sub_comment_path(@question, comment), method: "get", class: "b-margin" %>
          <% if comment.user == current_user %>
            <div class="card-action remove-margin">
              <%= link_to "Edit", edit_admin_question_comment_path(@question, comment), method: 'get' %>
              <%= link_to "Delete", admin_question_comment_path(@question, comment), method: 'delete' %>
            </div>
          <% else %>
            <div class="card-action remove-margin">
              <%= link_to "Delete", admin_question_comment_path(@question, comment), method: 'delete' %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <% comment.sub_comments.each_with_index do |sub_comment, index| %>
      <div class="center-align show-c" id="sub_comment-<%= index + 1 %>">
        <div class="col s12 subcomment-size">
          <% if sub_comment.user.admin? %>
            <div class="card blue">
          <% else %>
            <div class="card blue-grey">
          <% end %>
            <div class="card-content white-text">
              <p><%= sub_comment.content %></p></br>
              <p>Submitted by: <%= sub_comment.user.first_name.capitalize %> <%= sub_comment.user.last_name.capitalize[0] %>.</p>
            </div>
            <% if sub_comment.user == current_user %>
              <div class="card-action remove-margin">
                <%= link_to "Edit", edit_admin_question_comment_sub_comment_path(@question, comment, sub_comment), method: 'get' %>
                <%= link_to "Delete", admin_question_comment_sub_comment_path(@question, comment, sub_comment), method: 'delete', class: "delete-text" %>
              </div>
            <% else %>
              <div class="card-action remove-margin">
                <%= link_to "Delete", admin_question_comment_sub_comment_path(@question, comment, sub_comment), method: 'delete', class: "delete-text" %>
              </div>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  <% end %>
</section>