config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'questions#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'

  resources :users, only: [:new, :create]
  
  resources :questions do
    resources :comments, only: [:new, :create, :edit, :update, :destroy] do
      resources :sub_comments, only: [:new, :create, :edit, :update, :destroy]
    end
  end

  namespace :admin do
    resources :questions, only: [:show, :destroy] do
      resources :answers, only: [:create, :edit, :update, :destroy]
      resources :comments, only: [:new, :create, :edit, :update, :destroy] do
        resources :sub_comments, only: [:new, :create, :edit, :update, :destroy]
      end
    end
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ParkingLot</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav>
      <div class="nav-wrapper">
        <%= link_to 'ParkingLot', questions_path, class:"brand-logo logo-shift" %>
        <div class="brand-logo center">
          <ul>
            <li>
              <% if current_admin? %>
                <div class="minimize-log">Admin logged in as: <%= current_user.first_name.capitalize %></div>
              <% elsif current_user %>
                <div class="minimize-log">Logged in as: <%= current_user.first_name.capitalize %></div>
              <% end %>
            </li>
          </ul>
        </div>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <% if current_user %>
            <li><%= link_to 'Log Out', logout_path, method: 'post' %></li>
          <% else %>
            <li><%= link_to 'Log In', login_path %></li>
            <li><%= link_to 'Register', new_user_path %></li>
          <% end %>
        </ul>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>